### ISSUE TITLE
browser support?

### ISSUE THREAD

**Issue by vvo** [webmodules/jsonp#17]
Hi, do you know what browsers/versions you are compatible with?

I am thinking about old IES of course.

Thanks

**Comment by feross** [comment]
@vvo That's a good question.

@TooTallNate @rauchg I'm happy to set up Sauce Labs testing like we have on [`buffer`](https://github.com/feross/buffer/blob/master/README.md) so we can have a nice badge ;) Add me as a collaborator?

**Comment by rauchg** [comment]
done

**Comment by rauchg** [comment]
btw we use and love zuul by @defunctzombie, see other repos

**Comment by TooTallNate** [comment]
@vvo And fwiw, this module should be very cross-browser compatible, all the way down to IE6 even.

It only relies on `<script>` tag support which is basically every browser.

**Comment by feross** [comment]
@rauchg Yeah, zuul is awesome! Was that a yes, you want me to add a badge? Or you gonna do it?

**Comment by rauchg** [comment]
Go ahead. Thanks a lot <3

**Comment by feross** [comment]
Done: https://github.com/webmodules/jsonp/pull/19
