### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by paladosss** [webmodules/jsonp#39]
When i doing request to Google Matrix services i get this error.
```
Uncaught SyntaxError: Unexpected token :
```
Help please, cause i don't understand what to do!

**Comment by summer-yyyn** [comment]
请问你这个解决了吗？

**Comment by frwupeng517** [comment]
same problem and i can't find any unexpected : anywhere

**Comment by wshirey** [comment]
@paladosss I had the same issue until I found out that I was returning a JSON response without the callback function. Make sure all your responses have the callback function wrapping your response.

**Comment by mojereliev** [comment]
Just use `{param: 'c'}` in options.

**Comment by farhansalam** [comment]
@mojereliev this is not working either

**Comment by SiZapPaaiGwat** [comment]
Check your arguments, make sure you just put all your info in `param` and do not set name in `opt`.

```js
jsonp(url, {
    param: `key=value&key1=value1&callback`
    // no need to set name, it will make you confused
}, (err, json) => {
    // code
})
```

**Comment by seleckis** [comment]
Same here. I see that jsonp adds `=__jp0:1` at the end of the query, maybe that is a problem?

**Comment by xdlover** [comment]
Maybe your callback function name is not the same as the BackEngineer

**Comment by gdutleung** [comment]
You can set `format='jsonp'` in your request params on condition that the Server-side supported.

**Comment by Empire-T9** [comment]
make sure the server-side support jsonp, then you can use this plugin.

**Comment by BkunS** [comment]
I use jsonp as the workaround of CORS, but got the this error. I guess it's because the server is giving back json response instead of jsonp and the jsonp parser couldn't parse it. Though I can see the json response from console under this error message, is there anyway to access this response from code discarding the syntax error?
